seed: 4

optimizer:
  lr: 0.0001
  weight_decay: 0.001

lr_scheduler:
  step_size: 10
  gamma: 0.5

training:
  num_epochs: 50
  device: 'cuda'
  batch_size: 8
  augmentation: True
  model: "SwinUNet"   # Options: "Unet_Basic", "UNet_with_Residual", "AttentionUNet", "SwinUNet"

data:
  gdrive_url: "https://drive.google.com/file/d/13CnsJQrApAs8VDU7H2EhCezDPNhfazrX/view?usp=sharing"
  kaggle_dataset_name: "mateuszbuda/lgg-mri-segmentation"
  train_ratio: 0.8
  valid_ratio: 0.199999


paths:
  saves_root: ./saves/SwinUNet
  weights_root: ./weights/SwinUNet
  plots_root: ./plots/SwinUNet
  data:
    dataset_dir: ./Dataset/unzipped
    zip_path: ./Dataset/lgg-mri-segmentation.zip
